/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#ffffff',
        'on-primary': '#000000',
        ink: '#ffffff',
        body: '#a0a0a0',
        mute: '#666666',
        faint: '#333333',
        hairline: '#222222',
        'hairline-soft': '#111111',
        canvas: '#000000',
        'canvas-elevated': '#0a0a0a',
        link: '#3291ff',
        'link-deep': '#0070f3',
        'link-soft': 'rgba(0, 112, 243, 0.15)',
        error: '#ee0000',
        'error-deep': '#c50000',
        warning: '#f5a623',
        'warning-soft': '#ffefcf',
        'warning-deep': '#ab570a',
        violet: '#7928ca',
        'violet-soft': '#d8ccf1',
        cyan: '#50e3c2',
        'cyan-soft': '#aaffec',
        pink: '#ff0080',
        magenta: '#eb367f',
        'gradient-develop-start': '#007cf0',
        'gradient-develop-end': '#00dfd8',
        'gradient-preview-start': '#7928ca',
        'gradient-preview-end': '#ff0080',
        'gradient-ship-start': '#ff4d4d',
        'gradient-ship-end': '#f9cb28',
      },
      borderRadius: {
        none: '0px',
        sm: '6px',
        md: '12px',
        lg: '16px',
        'pill-category': '64px',
        pill: '100px',
        full: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '40px',
        '3xl': '64px',
        '4xl': '96px',
        section: '128px',
      },
      fontFamily: {
        sans: ['Geist', 'Arial', 'sans-serif'],
        mono: ['Geist Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
    },
  },
  plugins: [],
}
